### ISSUE TITLE
Ground-truth localization details

### ISSUE THREAD

**Issue by tpet** [hilti-challenge/Hilti-SLAM-Challenge-2022#11]
Thanks for this interesting dataset. Could you provide details on how was the ground-truth localization obtained? Was is similar to the previous year challenge (measured by total station)?

**Comment by hilti-challenge** [comment]
This year we used a survey-grade laserscanner (Z+F Imager 5016) to scan all locations. The individual groundtruth points are extracted from the scan (using laserscanner targets)

**Comment by tpet** [comment]
And how are you going to obtain ground-truth localization from that?

**Comment by hilti-challenge** [comment]
similar to last year, but we replaced the total station with laser-scanner targets like the one in the picture. 
![image](https://user-images.githubusercontent.com/98919589/169007011-b26c8854-787f-41a1-8aae-dca60df5e2de.png)

We "revisited" the same physical point on the ground with our lidar-camera-hardware

**Comment by YoshuaNava** [comment]
Was this the source of the ground truth trajectory for exp03-06 (which is said to be different and have an error of 1-3cm in the website), or for the whole challenge (to align against before computing the error at the control points)?

**Comment by IamPhytan** [comment]
How did you managed to scan targets that are not visible from the start of the runs (like in the cupola) ? Did you compute the transformation between each pose of the scanner ? If yes, how ?

**Comment by bedaberner** [comment]
> Was this the source of the ground truth trajectory for exp03-06 (which is said to be different and have an error of 1-3cm in the website), or for the whole challenge (to align against before computing the error at the control points)?

For the ground truth trajectory IPC was used to compare the lidar data to the Laserscan. This allowed us to create a dense trajectory but includes one of the sensors into the ground truth.
When comparing the dense ground truth generated by this method to the static targets measured directly in the laserscan, errors between 1-3cm resulted. This method was not at all involved in the final evaluation.



> How did you managed to scan targets that are not visible from the start of the runs (like in the cupola) ? Did you compute the transformation between each pose of the scanner ? If yes, how ?

We used many scans to create a complete pointcloud of the areas. They were combined using the usual workflow of the laserscanner (Target, ICP and plane matching, search for scantra if you are interested in the actual software used).

You can also watch [this video](https://www.youtube.com/watch?v=-LMq3zU47Pw) to see a bit of the scanning and the resulting laserscan.
