### ISSUE TITLE
calibration issue

### ISSUE THREAD

**Issue by snakehaihai** [hilti-challenge/Hilti-SLAM-Challenge-2022#13]
Hi
According to your file
![image](https://user-images.githubusercontent.com/6070995/167881929-a5e55e5f-bc6e-4ca0-b0bf-06dcfd152727.png)
The imu and LIDAR are 180 degree apart around X axis

However, based on your calibration file you provided, 

![image](https://user-images.githubusercontent.com/6070995/167881985-9d9d3b71-1e3b-48da-b3b0-0047e9edbbac.png)

Its 90 degree off? 

![image](https://user-images.githubusercontent.com/6070995/167882251-26d9666b-6670-4f75-8d4b-598e889eabb4.png)

Can you guys help to explain this?

And also how did you guys use the kalibra, I tried to use parser from https://github.com/sevensense-robotics/alphasense_stereo_demo  to generate parameter and test out the fisheye undistort 

and it says

```
Initializing node failed due to Camera right must be right in the coordinate frame of left camera.. The file "/home/av/alphasense_ws/src/alphasense_stereo_demo/alphasense_stereo/config/calib_3_cam0-1-camchain-imucam.yaml" is not a valid calibration fil

```

Are you giving correct kalibra file format?

**Comment by snakehaihai** [comment]
ok 1st problem solved. this is the actual lidar orientation
camera 0 z front, y right, x down.
Therefore LIDAR -y front, x left and z up
The rough direction in the yaml file is correct. But orientation seems not calibrated but rather handpicked number. 

![image](https://user-images.githubusercontent.com/6070995/167888337-63558a9f-dd98-4b81-83af-88b97d52576c.png)


both of the figure provided by hilti team are wrong and misleading. The newer one doesn`t even follow the right-hand rule

![image](https://user-images.githubusercontent.com/6070995/167887992-b78a1544-0ba6-4e82-9ede-e7f510383eda.png)

![image](https://user-images.githubusercontent.com/6070995/167888020-2164b147-52e9-4e16-9c9c-26fd199d352a.png)

**Comment by mcamurri** [comment]
Dear @snakehaihai please accept my apologies for responding so late. Indeed both diagrams above are wrong. A mistake was made when changing the picture from the standard vehicle convention (x-forward, y-left, z-up) to the actual convention used by HESAI, which has x-left, y-back, z-up:
![image](https://user-images.githubusercontent.com/13381545/203667508-194ca994-e67e-435d-9b8a-cba7352018f6.png)

The diagram has now been updated.

Hope the issue can be closed now?
