### ISSUE TITLE
Will the exp01, exp02, and exp03 be used for the final evaluation? 

### ISSUE THREAD

**Issue by LimHyungTae** [hilti-challenge/Hilti-SLAM-Challenge-2022#14]
Hello there, as an extension of #issue10 (https://github.com/Hilti-Research/Hilti-SLAM-Challenge-2022/issues/10)

What about exp01, exp02, and exp03? Are these still used for the final scoring?

I'm curious because HILTI 2022 challenge provides the report that includes exp01, exp02, and exp03.

Thank you!

**Comment by mauricefallon** [comment]
see here:
https://github.com/Hilti-Research/Hilti-SLAM-Challenge-2022/issues/12#issuecomment-1127574885
