### ISSUE TITLE
Is the Hesai Lidar point cloud motion-compensated?

### ISSUE THREAD

**Issue by YoshuaNava** [hilti-challenge/Hilti-SLAM-Challenge-2022#15]
Hi!
I wanted to enquire on whether the Hesai Pandar point cloud shipped with the dataset has been de-skewed / motion-compensated.

Thanks a lot.

**Comment by LimHyungTae** [comment]
Hello there, I think that cloud points were not de-skewed in the rosbag files. It is literally raw point cloud.

**Comment by hilti-challenge** [comment]
yes, it is the raw point cloud.
