### ISSUE TITLE
Exp16 6dof GT file timestamp is not right with bag  

### ISSUE THREAD

**Issue by wwtinwhu** [hilti-challenge/Hilti-SLAM-Challenge-2022#19]
Hello @lintong-zhang , thanks for your great work on this outstanding datasets! I found that the exp16's 6dof gt's timestamp does not confirm to the bag timestamp. Hope you guys check it out and update it, thanks!

**Comment by hilti-challenge** [comment]
Thanks for noticing! Should be fixed now.
