### ISSUE TITLE
Where to find the calibration file of Hilti SLAM Dataset 2021?

### ISSUE THREAD

**Issue by ouyangwl** [hilti-challenge/Hilti-SLAM-Challenge-2022#2]
Dear developers, thanks for your amazing work!

I'm trying to use the dataset to test my algorithm, but I didn't find the link to download the calibration file of Hilti SLAM Dataset 2021. Can you please share the calibration file of Hilti SLAM Dataset 2021? Thank you very much!

Best regards.

**Comment by hilti-challenge** [comment]
Hi,
we provide the raw [calibration data](https://storage.googleapis.com/hsc2022/calib_03_2022-03-02-11-27-22.bag) + [calibration board description](https://storage.googleapis.com/hsc2022/april_grid_2500x1500_7x12_15cm.yaml) for camera calibration as well as the Kalibr results for the [individual cameras](https://storage.googleapis.com/hsc2022/calibration/2022322_calibration_files.zip) (with respect to the imu). The zip file also contains the extrinsic parameters between lidar and imu.

Alternatively, you can also use the [CAD ](https://storage.googleapis.com/hsc2022/cad/Phasma25.stl) as an initial guess.

Hope you find this information useful.

**Comment by ouyangwl** [comment]
Thank you for your reply.
But I noticed that the file you provided  is the calibration file of Hilti SLAM Dataset 2022, may I have the calibration file of Hilti SLAM Dataset 2021?

**Comment by hilti-challenge** [comment]
You can download the calibration file for the Hilti Dataset 2021 [here](https://storage.googleapis.com/hilti_challenge/Calibration/calibration_02.yaml). I fixed the broken link on the homepage - thanks for noticing.

**Comment by ouyangwl** [comment]
Wow, I have seen that. Thank you very much!
