### ISSUE TITLE
Coordinate systems of the IMU

### ISSUE THREAD

**Issue by gogojjh** [hilti-challenge/Hilti-SLAM-Challenge-2022#3]
Hi, thanks for holding this challenge. 
Could you provide a figure or explanation about the coordinate system of the IMU?
The common coordinate system of an IMU should be (right-hand): x forward, y left, z upward. It seems that the IMU in this competition does not follow this rule.
Thanks.

**Comment by hilti-challenge** [comment]
Hi, we will provide a figure showing the frames of the different sensors, hope you will find that useful.
