### ISSUE TITLE
a clear coordinate system definition

### ISSUE THREAD

**Issue by JokerJohn** [hilti-challenge/Hilti-SLAM-Challenge-2022#4]
Hi, thanks for your work. Can you give a clear coordinate system definition file, similar to the KITTI dataset, which I did not find on the official website?
![image](https://user-images.githubusercontent.com/25702851/161296220-c29888e1-95cb-4ee9-b3a9-cda52907063b.png)
![image](https://user-images.githubusercontent.com/25702851/161296280-d3332e68-acd8-4e0c-9236-3e9f8a2f13b2.png)

**Comment by hilti-challenge** [comment]
Hi, We are currently working on a similar definition.

**Comment by hilti-challenge** [comment]
Hi, here you can see the diagram:
![image](https://user-images.githubusercontent.com/98919589/161942337-7a04e6f4-0a9c-4239-b33a-44a2679766db.png)

**Comment by JokerJohn** [comment]
According to the debugging results of our LIO algorithm in the datasets(exp04/05/06/calib_03), the coordinate system of the lidar and IMU is confirmed as shown in the figure below, in which the coordinate system of the Pandar lidar is different from the REP105 convention. Its xyz correspond to the left, back, and up directions, respectively. It is slightly different from the diagram you provided.
![8fa85ad74f6255802937f9470775774](https://user-images.githubusercontent.com/25702851/161970853-f762f7c7-8876-463f-b58e-85622c87f891.jpg)

**Comment by gogojjh** [comment]
An additional comment on the calibration diagram.
In this diagram, the X, Y, Z axes of the LiDAR are indicating forward, leftward, and upward. It does not fit the calibration parameters in ```lidar_calibration.yaml```. In this file, the X, Y, Z axes should indicate leftward, backward, and upward respectively.

**Comment by mcamurri** [comment]
@gogojjh  and @JokerJohn  you are both correct. 
I have also updated the corresponding URDF, here:  https://github.com/Hilti-Research/hesai_description/commit/64633725c701c2763c5787257f4e32b7bc3067d9
I have updated the diagram, sorry about the inconvenience.

Regarding the conventions, yes the recommendation 105 is to have x-forward, y-left and z-up. 
However, the raw data are expressed according to the manufacturer's specifications of the sensors (which are unfortunately different), and we preferred to keep them as they are instead of manipulating them by adding extra rotations.

**Comment by gogojjh** [comment]
Thanks a lot!

**Comment by YoshuaNava** [comment]
@mcamurri In the [commit you linked](https://github.com/Hilti-Research/hesai_description/commit/64633725c701c2763c5787257f4e32b7bc3067d9) you don't use the frame name in the Lidar message ("PandarXT-32"), but rather "pandar" -> 
![image](https://user-images.githubusercontent.com/7463211/168802084-b9b97cb5-8af1-4999-a200-9654ea873716.png)

Is this on purpose?

**Comment by mcamurri** [comment]
Sorry because the default value from the driver is `pandar`, I changed that without realising the frame in the HILTI rosbags is `PandarXT-32`. I'm going to fix that now.

**Comment by YoshuaNava** [comment]
@mcamurri I get the following error after trying to launch `view_urdf.launch` from the packages linked in this repo's README:

![image](https://user-images.githubusercontent.com/7463211/168883408-5e6b49af-7145-494e-aeb2-37c20ca2f6aa.png)

**Comment by mcamurri** [comment]
@YoshuaNava my apologies, can you please try this branch [here](https://github.com/Hilti-Research/alphasense_description/tree/add-calibration-converter). If that works, I will merge it.
