### ISSUE TITLE
Error submission

### ISSUE THREAD

**Issue by hellovuong** [hilti-challenge/Hilti-SLAM-Challenge-2022#6]
Hello, thank you for organize this challenge. I run into error when trying to submit. After submit zip file and report. The score appears to have error as following: 
`python: can't open file '/var/task/evaluation-2022/batch_evaluation.py': [Errno 2] No such file or directory`
My zip file includes:

- exp_04_construction_upper_level_easy_2_2022-03-03-11-48-59.txt
- exp_05_construction_upper_level_easy_2022-03-03-11-46-10.txt
- exp_06_construction_upper_level_hard_2022-03-03-12-08-37.txt

Can you take a look at it if anything wrong?
Thank you in advance

**Comment by hemi86** [comment]
We are working on it, expect an update next week!

**Comment by hellovuong** [comment]
Thank you, looking forward to the update.

**Comment by hilti-challenge** [comment]
the automatic evaluation system should be functional right now.

**Comment by IamPhytan** [comment]
On the same topic, I tried to submit my results and I got the following error :

> Traceback (most recent call last):   File "/var/task/evaluation-2022/batch_evaluation.py", line 224, in <module>     evaluate_submission(submission_path, groundtruth_path)   File "/var/task/evaluation-2022/batch_evaluation.py", line 87, in evaluate_submission     ape_stats, dense_trajectory, traj_est_aligned, traj_ref = evaluate(est_file, ref_file,submission_path)   File "/var/task/evaluation-2022/evaluation.py", line 240, in evaluate     umeyama_parameters = traj_est_aligned.align(traj_ref_sync, correct_scale=False, correct_only_scale=False)   File "/var/task/evo/core/trajectory.py", line 203, in align     r_a, t_a, s = geometry.umeyama_alignment(self.positions_xyz.T,   File "/var/task/evo/core/geometry.py", line 70, in umeyama_alignment     raise GeometryException("Degenerate covariance rank, " evo.core.geometry.GeometryException: Degenerate covariance rank, Umeyama alignment is not possible

Is this an error on the server ? Or is our data not coherent with what is accepted by the server ?

**Comment by hellovuong** [comment]
Hi @IamPhytan I tried to submit this afternoon, everything works well. I think you should check the file formats. Be sure it follows the submit instructions

**Comment by IamPhytan** [comment]
Yes, I found out it's not an error related to the website, but most probably an error in my trajectories. Thanks for the input @hellovuong
