### ISSUE TITLE
what's the measure_rate of IMU?

### ISSUE THREAD

**Issue by JokerJohn** [hilti-challenge/Hilti-SLAM-Challenge-2022#7]
We use the IMU calibration data. When testing the performance of the IMU, we know the frequency of the IMU topic（400hz）, but we also need to know the measure rate of the IMU. As far as I know, this data is configured in the IMU driver. Colud you provide it to us? 
![image](https://user-images.githubusercontent.com/25702851/165692629-50dd8486-07dd-4b11-a74e-aca9bfb4d7cb.png)

**Comment by hilti-challenge** [comment]
The internal measurement frequency of the IMU is ~2 kHz. Depending on the selected output frequency, 5, 10 or 20 samples are averaged. In our case (400Hz), 5 samples are averaged.
