### ISSUE TITLE
Submission - New bagfiles not evaluated

### ISSUE THREAD

**Issue by IamPhytan** [hilti-challenge/Hilti-SLAM-Challenge-2022#8]
Hello,

I recently tried to submit our trajectories for the bagfiles that were added to the website yesterday (Wednesday).
Yet, the evaluation system only seems to evaluate the files that have the same names as the older bagfiles (`exp*_construction_upper_level_*_2022-03-03*.txt`).

Do you know when we will be able to submit our trajectories for the new bagfiles (including the Sheldonian Theatre) ?

Thanks !

**Comment by bedaberner** [comment]
Hi 

I just updated the evaluation script so the new name format  will be accepted for the initial 3 datasets (exp04 to06, the old name should also still work).
Additionally I have added datasets exp01 to exp03 so they will also be evaluated now.

For the Sheldonian, the ground truth still requires some processing but it should be ready sometime next week.

**Comment by IamPhytan** [comment]
Ok, thank you very much @bedaberner ! 
How about exp07 ?

**Comment by bedaberner** [comment]
Also next week

**Comment by hilti-challenge** [comment]
please check my answer [here](https://github.com/Hilti-Research/Hilti-SLAM-Challenge-2022/issues/12#issuecomment-1122049000)
